// navigation
export const SET_CURRENT_CONTAINER = 'SET_CURRENT_CONTAINER';

// login
export const SET_CONFIRM_CODE = 'SET_CONFIRM_CODE';

// user
export const SET_USER = 'SET_USER';
export const SET_USER_CREDENTIAL = 'SET_USER_CREDENTIAL';
export const CREATE_USER = 'CREATE_USER';

// inn
export const FETCH_INN = 'FETCH_INN';
export const ADD_INN = 'ADD_INN';
export const INN_SHOW_LOADING = 'INN_SHOW_LOADING';
export const REMOVE_ALL_INN = 'REMOVE_ALL_INN';
export const SET_IS_END = 'SET_IS_END';

export const FETCH_LOGISTIC = 'FETCH_LOGISTIC';
export const LOGISTIC_SET_END = 'LOGISTIC_SET_END';
export const ADD_LOGISTIC = 'ADD_LOGISTIC';
export const LOGISTIC_IS_LOADING = 'LOGISTIC_IS_LOADING';
export const LOGISTIC_RELOAD_LIST = 'LOGISTIC_RELOAD_LIST';
export const LOGISTIC_SET_LAST = 'LOGISTIC_SET_LAST';

// roommate
export const FETCH_ROOMMATE = 'FETCH_ROOMMATE';
export const ROOMMATE_SET_END = 'ROOMMATE_SET_END';
export const ADD_ROOMMATE = 'ADD_ROOMMATE';
export const ROOMMATE_IS_LOADING = 'ROOMMATE_IS_LOADING';
export const ROOMMATE_RELOAD_LIST = 'ROOMMATE_RELOAD_LIST';
export const ROOMMATE_SET_LAST = 'ROOMMATE_SET_LAST';
