// navigation
export const SET_CURRENT_CONTAINER = 'SET_CURRENT_CONTAINER';

// login
export const SET_CONFIRM_CODE = 'login/SET_CONFIRM_CODE';

// user
export const SET_USER = 'user/SET_USER';
export const SET_USER_CREDENTIAL = 'user/SET_USER_CREDENTIAL';
export const CREATE_USER = 'user/CREATE_USER';

// inn
export const FETCH_INN = 'inn/FETCH_INN';
export const FETCH_INN_SUCCESS = 'inn/FETCH_INN_SUCCESS';
export const FETCH_INN_FAIL = 'inn/FETCH_INN_FAIL';

export const FETCH_MY_INN = 'inn/FETCH_MY_INN';
export const FETCH_MY_INN_SUCCESS = 'inn/FETCH_MY_INN_SUCCESS';
export const FETCH_MY_INN_FAIL = 'inn/FETCH_MY_INN_FAIL';

export const CREATE_INN = 'inn/CREATE_INN';
export const CREATE_INN_SUCCESS = 'inn/CREATE_INN_SUCCESS';
export const CREATE_INN_FAIL = 'inn/CREATE_INN_FAIL';

export const DELETE_INN = 'inn/DELETE_INN';
export const DELETE_INN_SUCCESS = 'inn/DELETE_INN_SUCCESS';
export const DELETE_INN_FAIL = 'inn/DELETE_INN_FAIL';

export const INN_SHOW_LOADING = 'inn/INN_SHOW_LOADING';
export const SET_IS_END = 'inn/SET_IS_END';
export const INN_SET_lAST = 'inn/INN_SET_LAST';
export const INN_RELOAD_LIST = 'inn/INN_RELOAD_LIST';
export const UPDATE_INNS = 'inn/UPDATE_INNS';
export const UPDATE_MY_INNS = 'inn/UPDATE_MY_INNS';

// logistic
export const FETCH_LOGISTIC = 'logistic/FETCH_LOGISTIC';
export const FETCH_LOGISTIC_SUCCESS = 'logistic/FETCH_LOGISTIC_SUCCESS';
export const FETCH_LOGISTIC_FAIL = 'logistic/FETCH_LOGISTIC_FAIL';

export const FETCH_MY_LOGISTIC = 'logistic/FETCH_MY_LOGISTIC';
export const FETCH_MY_LOGISTIC_SUCCESS = 'logistic/FETCH_MY_LOGISTIC_SUCCESS';
export const FETCH_MY_LOGISTIC_FAIL = 'logistic/FETCH_MY_LOGISTIC_FAIL';

export const CREATE_LOGISTIC = 'logistic/CREATE_LOGISTIC';
export const CREATE_LOGISTIC_SUCCESS = 'logistic/CREATE_LOGISTIC_SUCCESS';
export const CREATE_LOGISTIC_FAIL = 'logistic/CREATE_LOGISTIC_FAIL';

export const UPDATE_LOGISTIC = 'logistic/UPDATE_LOGISTIC';
export const UPDATE_LOGISTIC_SUCCESS = 'logistic/UPDATE_LOGISTIC_SUCCESS';
export const UPDATE_LOGISTIC_FAIL = 'logistic/UPDATE_LOGISTIC_FAIL';

export const DELETE_LOGISTIC = 'logistic/DELETE_LOGISTIC';
export const DELETE_LOGISTIC_SUCCESS = 'logistic/DELETE_LOGISTIC_SUCCESS';
export const DELETE_LOGISTIC_FAIL = 'logistic/DELETE_LOGISTIC_FAIL';

export const LOGISTIC_SET_END = 'logistic/LOGISTIC_SET_END';
export const LOGISTIC_RELOAD_LIST = 'logistic/LOGISTIC_RELOAD_LIST';
export const LOGISTIC_SET_LAST = 'logistic/LOGISTIC_SET_LAST';
export const LOGISTIC_RESET_CREATE_LOGISTIC_STATUS =
  'logistic/LOGISTIC_RESET_CREATE_LOGISTIC_STATUS';
export const LOGISTIC_RESET_UPDATE_LOGISTIC_STATUS =
  'logistic/LOGISTIC_RESET_UPDATE_LOGISTIC_STATUS';
export const LOGISTIC_RESET_DELETE_LOGISTIC_STATUS =
  'logistic/LOGISTIC_RESET_DELETE_LOGISTIC_STATUS';

// message
export const FETCH_LAST_MESSAGES = 'message/FETCH_LAST_MESSAGE';
export const FETCH_DETAIL_MESSAGES = 'message/FETCH_DETAIL_MESSAGE';
export const SEND_MESSAGE = 'message/SEND_MESSAGE';
export const MESSAGE_SET_LAST = 'message/MESSAGE_SET_LAST';
export const DETAIL_MESSAGE_SET_LAST = 'message/DETAIL_MESSAGE_SET_LAST';
export const MESSAGE_SET_END = 'message/MESSAGE_SET_END';
export const MESSAGE_DETAIL_SET_END = 'message/MESSAGE_DETAIL_SET_END';
export const CHANGE_MESSAGE = 'message/CHANGE_MESSAGE';
export const SET_CHANGE_MESSAGES = 'message/SET_CHANGE_MESSAGES';

// roommate
export const FETCH_ROOMMATE = 'roommate/FETCH_ROOMMATE';
export const FETCH_ROOMMATE_SUCCESS = 'roommate/FETCH_ROOMMATE_SUCCESS';
export const FETCH_ROOMMATE_FAIL = 'roommate/FETCH_ROOMMATE_FAIL';

export const FETCH_MY_ROOMMATE = 'roommate/FETCH_MY_ROOMMATE';
export const FETCH_MY_ROOMMATE_SUCCESS = 'roommate/FETCH_MY_ROOMMATE_SUCCESS';
export const FETCH_MY_ROOMMATE_FAIL = 'roommate/FETCH_MY_ROOMMATE_FAIL';

export const CREATE_ROOMMATE = 'roommate/CREATE_ROOMMATE';
export const CREATE_ROOMMATE_SUCCESS = 'roommate/CREATE_ROOMMATE_SUCCESS';
export const CREATE_ROOMMATE_FAIL = 'roommate/CREATE_ROOMMATE_FAIL';

export const UPDATE_ROOMMATE = 'roommate/UPDATE_ROOMMATE';
export const UPDATE_ROOMMATE_SUCCESS = 'roommate/UPDATE_ROOMMATE_SUCCESS';
export const UPDATE_ROOMMATE_FAIL = 'roommate/UPDATE_ROOMMATE_FAIL';

export const DELETE_ROOMMATE = 'roommate/DELETE_ROOMMATE';
export const DELETE_ROOMMATE_SUCCESS = 'roommate/DELETE_ROOMMATE_SUCCESS';
export const DELETE_ROOMMATE_FAIL = 'roommate/DELETE_ROOMMATE_FAIL';

export const CHANGE_ROOMMATE_ACTIVE = 'roommate/CHANGE_ROOMMATE_ACTIVE';
export const CHANGE_ROOMMATE_ACTIVE_SUCCESS =
  'roommate/CHANGE_ROOMMATE_ACTIVE_SUCCESS';
export const CHANGE_ROOMMATE_ACTIVE_FAIL =
  'roommate/CHANGE_ROOMMATE_ACTIVE_FAIL';

export const RESET_FETCH_ROOMMATE_STATUS =
  'roommate/RESET_FETCH_ROOMMATE_STATUS';
export const RESET_CREATE_ROOMMATE_STATUS =
  'roommate/RESET_CREATE_ROOMMATE_STATUS';
export const RESET_UPDATE_ROOMMATE_STATUS =
  'roommate/RESET_UPDATE_ROOMMATE_STATUS';
export const RESET_DELETE_ROOMMATE_STATUS =
  'roommate/RESET_DELETE_ROOMMATE_STATUS';

export const ROOMMATE_SET_END = 'roommate/ROOMMATE_SET_END';
export const ROOMMATE_RELOAD_LIST = 'roommate/ROOMMATE_RELOAD_LIST';
export const ROOMMATE_SET_LAST = 'roommate/ROOMMATE_SET_LAST';

// houseware
export const HOUSEWARE_CREATE_POST = 'houseware/HOUSEWARE_CREATE_POST';
export const HOUSEWARE_CREATE_POST_SUCCESS =
  'houseware/HOUSEWARE_CREATE_POST_SUCCESS';
export const HOUSEWARE_CREATE_POST_FAIL =
  'houseware/HOUSEWARE_CREATE_POST_FAIL';
export const FETCH_HOUSEWARES = 'houseware/FETCH_HOUSEWARES';
export const FETCH_HOUSEWARES_SUCCESS = 'houseware/FETCH_HOUSEWARES_SUCCESS';
export const FETCH_HOUSEWARES_FAIL = 'houseware/FETCH_HOUSEWARES_FAIL';
export const SET_END_OF_HOUSEWARES = 'houseware/SET_END_OF_HOUSEWARES';
export const RESET_LIST_HOUSEWARES = 'houseware/RESET_LIST_HOUSEWARES';
export const SET_LAST_HOUSEWARE = 'houseware/SET_LAST_HOUSEWARE';
export const SET_FETCH_HOUSEWARES = 'houseware/SET_FETCH_HOUSEWARES';
export const FETCH_MY_HOUSEWARES = 'houseware/FETCH_MY_HOUSEWARES';
export const FETCH_MY_HOUSEWARES_SUCCESS =
  'houseware/FETCH_MY_HOUSEWARES_SUCCESS';
export const FETCH_MY_HOUSEWARES_FAIL = 'houseware/FETCH_MY_HOUSEWARES_FAIL';
export const UPDATE_HOUSEWARE_IS_ACTIVE =
  'houseware/UPDATE_HOUSEWARE_IS_ACTIVE';
export const UPDATE_HOUSEWARE_IS_ACTIVE_SUCCESS =
  'houseware/UPDATE_HOUSEWARE_IS_ACTIVE_SUCCESS';
export const UPDATE_HOUSEWARE_IS_ACTIVE_FAIL =
  'houseware/UPDATE_HOUSEWARE_IS_ACTIVE_FAIL';
export const UPDATE_HOUSEWARE = 'houseware/UPDATE_HOUSEWARE';
export const UPDATE_HOUSEWARE_SUCCESS = 'houseware/UPDATE_HOUSEWARE_SUCCESS';
export const UPDATE_HOUSEWARE_FAIL = 'houseware/UPDATE_HOUSEWARE_FAIL';
export const RESET_CREATE_HOUSEWARE_STATUS =
  'houseware/RESET_CREATE_HOUSEWARE_STATUS';
export const RESET_UPDATE_HOUSEWARE_STATUS =
  'houseware/RESET_UPDATE_HOUSEWARE_STATUS';
