// navigation
export const SET_CURRENT_CONTAINER = 'SET_CURRENT_CONTAINER';

// login
export const SET_CONFIRM_CODE = 'SET_CONFIRM_CODE';

// user
export const SET_USER = 'SET_USER';
export const SET_USER_CREDENTIAL = 'SET_USER_CREDENTIAL';
export const CREATE_USER = 'CREATE_USER';

// inn
export const FETCH_INN = 'FETCH_INN';
export const ADD_INN = 'ADD_INN';
export const INN_SHOW_LOADING = 'INN_SHOW_LOADING';
export const SET_IS_END = 'SET_IS_END';
export const CREATE_INN = 'CREATE_INN';
export const INN_SET_lAST = 'INN_SET_lAST';
export const INN_RELOAD_LIST = 'INN_RELOAD_LIST';
export const FETCH_MY_INN = 'FETCH_MY_INN';
export const ADD_MY_INN = 'ADD_MY_INN';

export const FETCH_LOGISTIC = 'FETCH_LOGISTIC';
export const LOGISTIC_SET_END = 'LOGISTIC_SET_END';
export const ADD_LOGISTIC = 'ADD_LOGISTIC';
export const LOGISTIC_IS_LOADING = 'LOGISTIC_IS_LOADING';
export const LOGISTIC_RELOAD_LIST = 'LOGISTIC_RELOAD_LIST';
export const LOGISTIC_SET_LAST = 'LOGISTIC_SET_LAST';

export const FETCH_LAST_MESSAGES = 'FETCH_LAST_MESSAGE';
export const FETCH_DETAIL_MESSAGES = 'FETCH_DETAIL_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_SET_LAST = 'MESSAGE_SET_LAST';
export const DETAIL_MESSAGE_SET_LAST = 'DETAIL_MESSAGE_SET_LAST';
export const MESSAGE_SET_END = 'MESSAGE_SET_END';
export const MESSAGE_DETAIL_SET_END = 'MESSAGE_DETAIL_SET_END';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const SET_CHANGE_MESSAGES = 'SET_CHANGE_MESSAGES';
// roommate
export const FETCH_ROOMMATE = 'FETCH_ROOMMATE';
export const ROOMMATE_SET_END = 'ROOMMATE_SET_END';
export const ADD_ROOMMATE = 'ADD_ROOMMATE';
export const ROOMMATE_IS_LOADING = 'ROOMMATE_IS_LOADING';
export const ROOMMATE_RELOAD_LIST = 'ROOMMATE_RELOAD_LIST';
export const ROOMMATE_SET_LAST = 'ROOMMATE_SET_LAST';
