export const navigationName = {
  loading: 'loading',
  homeContainer: 'home-container',
  loginContainer: 'login-container',
  login: {
    login: 'login-login',
    loginWithPhoneNumber: 'login-with-phonenumber',
    confirmCode: 'confirm-code',
    additionalUserInfo: 'additional-user-info',
  },
  findInn: {
    findInn: 'inn-find-inn',
    createInn: 'inn-create-inn',
    innDetail: 'inn-inn-detail',
    myInn: 'inn-my-inn',
    viewProfile: 'inn-view-profile',
    chat: 'inn-chat',
  },
  logistic: {
    logistic: 'logistic-logistic',
    logisticDetail: 'logistic-logistic-detail',
    createLogistic: 'logistic-create-logistic',
    myLogistic: 'logistic-my-logistic',
    viewProfile: 'logistic-view-profile',
    chat: 'logistic-chat',
  },
  chat: {
    chat: 'chat-chat',
    chatDetail: 'chat-detail',
  },
  home: {
    chat: 'home-chat',
    profile: 'home-profile',
    roommate: 'home-roommate',
    houseware: 'home-houseware',
    logistic: 'home-logistic',
    inn: 'home-inn',
  },
  roommate: {
    roommate: 'roommate-roommate',
    post: 'roommate-post',
    myPost: 'roommate-my-post',
    profile: 'roommate-profile',
    chat: 'roommate-chat',
  },
  houseware: {
    houseware: 'houseware-houseware',
    createHouseware: 'houseware-create-houseware',
    myHouseware: 'houseware-my-houseware',
    profile: 'houseware-profile',
    chat: 'houseware-chat',
  },
};
