const translate = {
  continueWithFacebook: 'Tiếp tục với Facebook',
  continueWithPhoneNumber: 'Tiếp tục với số điện thoại',
  phoneNumber: 'Số điện thoại',
  continue: 'Tiếp tục',
  backEventHaveNotSet: 'backEvent have not set',
  name: 'Tên',
  birthday: 'Ngày sinh',
  email: 'Email',
  changeAvatar: 'Thay đổi hình đại diện',
  homeTown: 'Quê quán',
  job: 'Nghề nghiệp',
  social: 'Mạng xã hội',
  enterCode: 'Nhập mã xác thực',
  findInnDetail: 'Chi tiết trọ',
  seeMore: 'Xem thêm...',
  logisticDetail: 'Chi tiết xe',
  logisticService: 'Dịch vụ vận chuyển',
  logistic: {
    area: 'Khu vực:',
    price: 'Giá vận chuyển:',
    detail: 'Chi tiết:',
    contact: 'Liên hệ:',
  },
  chat: {
    chat: 'Chat',
  },
  roommate: {
    findRoommate: 'Tìm người ở ghép',
    post: 'Đăng bài viết',
    contentTitle: 'Nội dùng bài viết:',
    foundRoommate: 'Đã tìm được người ở cùng',
  },
  post: {
    innInfo: 'Thông tin phòng',
    innName: 'Tên trọ',
    innOwner: 'Chủ trọ',
    innPrice: 'Giá phòng',
    innAddress: 'Địa chỉ',
    innWaterPrice: 'Giá nước',
    innElectricPrice: 'Giá điện',
    innArea: 'Diện tích',
    innDeposit: 'Tiền cọc',
    post: 'Đăng',
  },
  city: 'Tỉnh/Thành phố',
  district: 'Quận/Huyện',
  ward: 'Phường/Xã',
  apply: 'Áp dụng',
};

export {translate};
