const translate = {
  continueWithFacebook: 'Tiếp tục với Facebook',
  continueWithPhoneNumber: 'Tiếp tục với số điện thoại',
  phoneNumber: 'Số điện thoại',
  continue: 'Tiếp tục',
  backEventHaveNotSet: 'backEvent have not set',
  name: 'Tên',
  birthday: 'Ngày sinh',
  email: 'Email',
  changeAvatar: 'Thay đổi hình đại diện',
  homeTown: 'Quê quán',
  job: 'Nghề nghiệp',
  social: 'Mạng xã hội',
  enterCode: 'Nhập mã xác thực',
  findInnDetail: 'Chi tiết trọ',
  seeMore: 'Xem thêm...',
  logisticDetail: 'Chi tiết xe',
  logisticService: 'Dịch vụ vận chuyển',
  new: 'Tạo',
  status: 'Trạng thái',
  save: 'Lưu',
  ownerInfo: 'Thông tin chủ trọ',
  innInfo: 'Thông tin trọ',
  available: 'Còn trống',
  unavailable: 'Hết phòng',
  otherInfos: 'Thông tin khác',
  image: 'Hình ảnh',
  inn: {
    myInn: 'Trọ của đã đăng',
    createInn: 'Đăng thông tin trọ',
  },
  logistic: {
    area: 'Khu vực:',
    price: 'Giá vận chuyển:',
    detail: 'Chi tiết:',
    contact: 'Liên hệ:',
    myLogistic: 'Dịch vụ của đã đăng',
  },
  chat: {
    chat: 'Chat',
  },
  roommate: {
    findRoommate: 'Tìm người ở ghép',
    post: 'Đăng bài viết',
    contentTitle: 'Nội dùng bài viết:',
    foundRoommate: 'Đã tìm được người ở cùng',
  },
  post: {
    innInfo: 'Thông tin phòng',
    innName: 'Tên trọ',
    innOwner: 'Chủ trọ',
    innPrice: 'Giá phòng',
    innAddress: 'Địa chỉ',
    innWaterPrice: 'Giá nước',
    innElectricPrice: 'Giá điện',
    innArea: 'Diện tích',
    innDeposit: 'Tiền cọc',
    post: 'Đăng',
    innWifi: 'Wifi',
    innGarage: 'Nhà giữ xe',
    innContact: 'Số điện thoại liên hệ',
    maxRoommate: 'Số người ở tối đa',
    furniture: 'Tiện ích',
    attention: 'Chú ý',
    notes: 'Mô tả chi tiết',
    addressPlaceholder: '25 Hai Bà Trưng, Quận 3, TP.HCM',
    airConditioner: 'Điều hòa',
    roomBed: 'Giường ngủ',
    roomCloset: 'Tủ áo quần',
    roomKetchen: 'Nhà bếp',
    roomPetsAllowed: 'Cho nuôi thú cưng',
    roomTivi: 'Tivi',
    roomRefrigerator: 'Tủ lạnh',
    roomWashingMachine: 'Máy giặt',
    window: 'Cửa sổ',
    logisticName: 'Tên dịch vụ vận chuyển',
    logisticInfo: 'Thông tin dịch vụ vận chuyển',
    logisticPrice: 'Giá',
    logisticOnwerInfo: 'Thông tin chủ xe',
    carOwner: 'Chủ xe',
    logisticArea: 'Khu vực hoạt động',
    pricePlaceholder: '1000000',
    areaPlaceholder: 'Bình Thạnh, Thủ Đức',
  },
  city: 'Tỉnh/Thành phố',
  district: 'Quận/Huyện',
  ward: 'Phường/Xã',
  apply: 'Áp dụng',
  cityPicker: {
    PLACEHOLDER: 'Chọn tỉnh/thành phố',
    SEARCH_PLACEHOLDER: 'Tìm kiếm...',
    SELECTED_ITEMS_COUNT_TEXT: 'd item(s) have been selected',
    NOTHING_TO_SHOW: 'Không có tỉnh nào để hiển thị',
  },
  statusPicker: {
    PLACEHOLDER: 'Trạng thái phòng',
    SELECTED_ITEMS_COUNT_TEXT: 'd item(s) have been selected',
  },
  districtPicker: {
    PLACEHOLDER: 'Chọn quận/huyện',
    SEARCH_PLACEHOLDER: 'Tìm kiếm...',
    SELECTED_ITEMS_COUNT_TEXT: 'd item(s) have been selected',
    NOTHING_TO_SHOW: 'Không có quận huyện nào để hiển thị',
  },
};

export {translate};
